import { ApiProperty } from '@nestjs/swagger';

export class ProblemDetailsDto {
  @ApiProperty({
    description: 'A URI reference that identifies the problem type',
    example: 'https://example.com/probs/validation-error'
  })
  type: string;

  @ApiProperty({
    description: 'A short, human-readable summary of the problem type',
    example: 'Validation Error'
  })
  title: string;

  @ApiProperty({
    description: 'The HTTP status code generated by the origin server',
    example: 400
  })
  status: number;

  @ApiProperty({
    description: 'A human-readable explanation specific to this occurrence of the problem',
    example: 'The request body contains invalid data'
  })
  detail: string;

  @ApiProperty({
    description: 'A URI reference that identifies the specific occurrence of the problem',
    example: '/api/checklists/invalid-id'
  })
  instance: string;

  @ApiProperty({
    description: 'Application-specific error code',
    example: 'CHECKLIST_NOT_FOUND',
    required: false
  })
  code?: string;
}
